epirus truffle generate --truffle-json ../packages/protocol/build/contracts/Accounts.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/Attestations.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/BlockchainParameters.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/DoubleSigningSlasher.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/DowntimeSlasher.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/Election.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/EpochRewards.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/Escrow.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/Exchange.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/FeeCurrencyWhitelist.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/Freezer.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/GasPriceMinimum.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/GoldToken.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/Governance.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/LockedGold.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/MultiSig.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/Random.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/Registry.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/Reserve.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/SortedOracles.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/StableToken.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/TransferWhitelist.json -o src/main/java -p org.celo.contractkit.contract
epirus truffle generate --truffle-json ../packages/protocol/build/contracts/Validators.json -o src/main/java -p org.celo.contractkit.contract
